item_dict = {'borax' :                  '9366', 
            'raziqsap' :                '9369',
            'hardened sap' :            '5532', 
            'coke' :                    '5530', 
            'petrified log' :           '7596', 
            'scheelite' :               '7596', 
            'cashmere fleece' :         '7600', 
            'raziqsand' :               '7598', 
            'procoptodon skin' :       '24244', 
            'g.a. wax' :               '24248', 
            'stardust cotton yarn' :   '24247',
            'tatara iron sand' :       '24246',
            'g.a. carbon rods' :       '24245',
            'high-gloss urushi' :      '24249',
            'heaven\'s eye vi' :       '18018',
            'savage aim vi' :          '18019',
            'savage might vi' :        '18020',
            'ground sloth pelt' :      '22421'}